apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/svachop/homelab.git
    path: ./charts/onepassword-connect
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword-connect
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
